# DEPRECATED: better creating docker container and then running it. so it does not deleted automatically
# update only on forced action
services:
  jupyter:
    build:
      context: .
      dockerfile: DockerfileRootPwd
      args:
        ROOT_PASSWORD: $JUPYTER_TOKEN
    ports:
      - $JUPYTERLAB_LISTEN_ADDR:8080
      - $JUPYTERLAB_LISTEN_ADDR_SSH:22
    volumes:
      - $DATAPATH:/data
      - ./logs:/var/log
      - ./home:/root
    environment:
      JUPYTER_TOKEN: $JUPYTER_TOKEN
    restart: $RESTART
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

