services:
  jupyter:
    build:
      context: .
      dockerfile: DockerfileRootPwd
      args:
        ROOT_PASSWORD: $JUPYTER_TOKEN
    ports:
      - $JUPYTERLAB_LISTEN_ADDR:8080
      - $JUPYTERLAB_LISTEN_ADDR_SSH:22
    volumes:
      - ./notebooks:/workspace/notebooks
      - /mnt/data/rpozzi-jupyterlab:/workspace/data
      - ./logs:/var/log
      - ./home:/root
    environment:
      JUPYTER_TOKEN: $JUPYTER_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

